version: '3.8'

services:
  hugo-site:
    build: .
    container_name: curriculum
    ports:
      - "${PORT}:80"
    restart: unless-stopped
    # volumes:
    #   - ./public:/usr/share/nginx/html:ro